// File: src/component/idcard/IDCardPdf.jsx
import { Document, Font, Image, Page, StyleSheet, Text, View } from '@react-pdf/renderer';
import { encode } from 'uqr';
import Oswald from '../result/pdffonts/Oswald-VariableFont_wght.ttf';
import roboto from '../result/pdffonts/RobotoRegular-3m4L.ttf';

Font.register({ family: 'Roboto', src: roboto });
Font.register({ family: 'Oswald', src: Oswald });

// -----------------------------------------------------------------------
// QR helper (same approach as StudentResults)
// -----------------------------------------------------------------------
function generateQRBase64(text) {
  const result = encode(text);
  const cells = result.data;
  const size = cells.length;
  const cellSize = 4;
  const padding = 16;
  const dimension = size * cellSize + padding * 2;

  let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${dimension} ${dimension}" width="${dimension}" height="${dimension}">`;
  svg += `<rect width="${dimension}" height="${dimension}" fill="white"/>`;

  for (let row = 0; row < size; row++) {
    for (let col = 0; col < size; col++) {
      if (cells[row][col]) {
        svg += `<rect x="${col * cellSize + padding}" y="${row * cellSize + padding}" width="${cellSize}" height="${cellSize}" fill="black"/>`;
      }
    }
  }

  svg += `</svg>`;

  const base64 = btoa(svg);
  return `data:image/svg+xml;base64,${base64}`;
}

const chunk = (arr, size) => {
  const out = [];
  for (let i = 0; i < arr.length; i += size) {
    out.push(arr.slice(i, i + size));
  }
  return out;
};

const PER_PAGE = 10;

// -----------------------------------------------------------------------
// Front of a single card
// -----------------------------------------------------------------------
const CardFront = ({ student, school, color, className, sessionLabel, logoUrl }) => {
  const qrText =
    `Student ID\n` +
    `Name: ${student.fullname || (student.firstname + ' ' + student.surname + ' ' + student.lastname)}\n` +
    `Reg No: ${student.regNo}\n` +
    `Class: ${className}\n` +
    `School: ${school.name || ''}\n` +
    (sessionLabel ? `Session: ${sessionLabel}` : '');

  const qrBase64 = generateQRBase64(qrText);

  return (
    <View style={cardStyle.card}>
      {/* Header band */}
      <View style={[cardStyle.headerBand, { backgroundColor: color }]}>
        <View style={cardStyle.logoSlot}>
          {logoUrl ? (
            <Image src={logoUrl} style={cardStyle.logoImage} />
          ) : null}
        </View>
        <Text style={cardStyle.headerSchoolName}>
          {school.name || 'SCHOOL NAME'}
        </Text>
        <Text style={cardStyle.headerCardType}>STUDENT ID</Text>
      </View>

      {/* Body */}
      <View style={cardStyle.frontBody}>
        <View style={cardStyle.photoColumn}>
          <View style={cardStyle.photoBox} />
          <Text style={cardStyle.signatureLine}>____________</Text>
          <Text style={cardStyle.signatureLabel}>Authorized Signature</Text>
        </View>

        <View style={cardStyle.detailsColumn}>
          <Text style={cardStyle.detailLine}>
            <Text style={cardStyle.detailLabel}>Name: </Text>
            <Text style={cardStyle.detailValue}>
              {student.fullname || (student.firstname + ' ' + student.surname + ' ' + student.lastname)}
            </Text>
          </Text>
          <Text style={cardStyle.detailLine}>
            <Text style={cardStyle.detailLabel}>Reg No: </Text>
            <Text style={cardStyle.detailValue}>{student.regNo || '-'}</Text>
          </Text>
          <Text style={cardStyle.detailLine}>
            <Text style={cardStyle.detailLabel}>Class: </Text>
            <Text style={cardStyle.detailValue}>{className || '-'}</Text>
          </Text>
          <Text style={cardStyle.detailLine}>
            <Text style={cardStyle.detailLabel}>Gender: </Text>
            <Text style={cardStyle.detailValue}>{student.gender || '-'}</Text>
          </Text>
          {sessionLabel ? (
            <Text style={cardStyle.detailLine}>
              <Text style={cardStyle.detailLabel}>Session: </Text>
              <Text style={cardStyle.detailValue}>{sessionLabel}</Text>
            </Text>
          ) : null}
        </View>

        <View style={cardStyle.qrColumn}>
          <Image src={qrBase64} style={cardStyle.qrImage} />
          <Text style={cardStyle.qrCaption}>SCAN</Text>
        </View>
      </View>

      {/* Brand line — bigger now */}
      <Text style={cardStyle.brandLine}>
        Generated by MiQwii Manager Student Portal
      </Text>
    </View>
  );
};

// -----------------------------------------------------------------------
// Back of a single card
// -----------------------------------------------------------------------
const CardBack = ({ student, school, color, className, logoUrl }) => (
  <View style={cardStyle.card}>
    {/* Header band */}
    <View style={[cardStyle.headerBand, { backgroundColor: color }]}>
      <View style={cardStyle.logoSlot}>
        {logoUrl ? (
          <Image src={logoUrl} style={cardStyle.logoImage} />
        ) : null}
      </View>
      <Text style={cardStyle.headerSchoolName}>
        {school.name || 'SCHOOL NAME'}
      </Text>
      <Text style={cardStyle.headerCardType}>ID BACK</Text>
    </View>

    {/* Body */}
    <View style={cardStyle.backBody}>
      <Text style={cardStyle.backLine}>
        <Text style={cardStyle.backLabel}>Motto: </Text>
        <Text style={cardStyle.backValue}>{school.motto || '-'}</Text>
      </Text>
      <Text style={cardStyle.backLine}>
        <Text style={cardStyle.backLabel}>Address: </Text>
        <Text style={cardStyle.backValue}>{school.address || '-'}</Text>
      </Text>
      <Text style={cardStyle.backLine}>
        <Text style={cardStyle.backLabel}>Phone: </Text>
        <Text style={cardStyle.backValue}>{school.contact || '-'}</Text>
      </Text>

      <View style={cardStyle.advisoryBox}>
        <Text style={cardStyle.advisoryTitle}>Advisory</Text>
        <Text style={cardStyle.advisoryText}>
          This card is the property of the school and must be surrendered on
          demand. If found, please return it to the school.
        </Text>
      </View>

      <Text style={cardStyle.backCardId}>
        Reg No: {student?.regNo || '-'}
      </Text>
    </View>

    <Text style={cardStyle.brandLine}>
      Generated by MiQwii Manager Student Portal
    </Text>
  </View>
);

// -----------------------------------------------------------------------
// Main document
//   Fronts: 10 per A4 page
//   Backs:  10 per A4 page (same size and arrangement as fronts)
// -----------------------------------------------------------------------
const IDCardPdf = ({
  students,
  school,
  className,
  sessionLabel,
  color = '#0e387a',
  logoUrl,
}) => {
  const frontPages = chunk(students, PER_PAGE);
  const backPages = chunk(students, PER_PAGE);

  return (
    <Document>
      {/* Fronts */}
      {frontPages.map((pageStudents, pageIndex) => (
        <Page key={`front-${pageIndex}`} size="A4" style={cardStyle.page}>
          <View style={cardStyle.grid}>
            {pageStudents.map((student, idx) => (
              <CardFront
                key={`f-${pageIndex}-${idx}-${student.id}`}
                student={student}
                school={school}
                color={color}
                className={className}
                sessionLabel={sessionLabel}
                logoUrl={logoUrl}
              />
            ))}
          </View>
        </Page>
      ))}

      {/* Backs — same chunking as fronts */}
      {backPages.map((pageStudents, pageIndex) => (
        <Page key={`back-${pageIndex}`} size="A4" style={cardStyle.page}>
          <View style={cardStyle.grid}>
            {pageStudents.map((student, idx) => (
              <CardBack
                key={`b-${pageIndex}-${idx}-${student.id}`}
                student={student}
                school={school}
                color={color}
                className={className}
                logoUrl={logoUrl}
              />
            ))}
          </View>
        </Page>
      ))}
    </Document>
  );
};

export default IDCardPdf;

// -----------------------------------------------------------------------
// Dimensions tuned so 2 × 5 cards fit on A4 without clipping
// -----------------------------------------------------------------------
const CARD_W = 240;
const CARD_H = 150;

const cardStyle = StyleSheet.create({
  page: {
    paddingTop: 12,
    paddingBottom: 12,
    paddingHorizontal: 16,
    backgroundColor: '#ffffff',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
  },

  // ---- shared card chrome (front and back identical box) ----
  card: {
    width: CARD_W,
    height: CARD_H,
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#333333',
    borderRadius: 6,
    overflow: 'hidden',
    flexDirection: 'column',
    backgroundColor: '#ffffff',
  },

  headerBand: {
    height: 30,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
 logoSlot: {
  width: 22, height: 22, borderRadius: 11,
  backgroundColor: '#ffffff',
  alignItems: 'center', justifyContent: 'center',
  marginRight: 5,
},
logoImage: {
  width: 20, height: 20, objectFit: 'contain',
},
  headerSchoolName: {
    flex: 1,
    fontFamily: 'Oswald',
    fontSize: 9,
    color: '#ffffff',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  headerCardType: {
    fontFamily: 'Oswald',
    fontSize: 7,
    color: '#ffffff',
    letterSpacing: 0.5,
  },

  // ---- front body ----
  frontBody: {
    flexDirection: 'row',
    flexGrow: 1,
    padding: 5,
    gap: 5,
  },
  photoColumn: {
    width: 54,
    alignItems: 'center',
  },
  photoBox: {
    width: 50,
    height: 60,
    borderWidth: 1,
    borderColor: '#555555',
    backgroundColor: '#f4f4f4',
  },
  signatureLine: {
    fontFamily: 'Roboto',
    fontSize: 7,
    color: '#555555',
    marginTop: 4,
  },
  signatureLabel: {
    fontFamily: 'Roboto',
    fontSize: 5.5,
    color: '#777777',
    textAlign: 'center',
  },
  detailsColumn: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  detailLine: {
    fontFamily: 'Roboto',
    fontSize: 7,
    marginBottom: 3,
    lineHeight: 1.25,
  },
  detailLabel: {
    color: '#555555',
    fontFamily: 'Roboto',
  },
  detailValue: {
    color: '#111111',
    fontWeight: 'bold',
    fontFamily: 'Roboto',
  },
  qrColumn: {
    width: 54,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrImage: {
    width: 48,
    height: 48,
  },
  qrCaption: {
    fontFamily: 'Roboto',
    fontSize: 5,
    color: '#666666',
    marginTop: 2,
    textAlign: 'center',
  },

  // ---- back body ----
  backBody: {
    flexGrow: 1,
    padding: 6,
  },
  backLine: {
    fontFamily: 'Roboto',
    fontSize: 7,
    marginBottom: 3,
    lineHeight: 1.25,
  },
  backLabel: {
    color: '#555555',
    fontFamily: 'Roboto',
  },
  backValue: {
    color: '#111111',
    fontWeight: 'bold',
    fontFamily: 'Roboto',
  },
  advisoryBox: {
    marginTop: 5,
    padding: 4,
    borderWidth: 1,
    borderColor: '#d0d0d0',
    borderRadius: 4,
    backgroundColor: '#fafafa',
  },
  advisoryTitle: {
    fontFamily: 'Oswald',
    fontSize: 6.5,
    fontWeight: 'bold',
    marginBottom: 2,
    color: '#333333',
  },
  advisoryText: {
    fontFamily: 'Roboto',
    fontSize: 6,
    color: '#555555',
    lineHeight: 1.3,
  },
  backCardId: {
    marginTop: 5,
    fontFamily: 'Roboto',
    fontSize: 6.5,
    color: '#666666',
    textAlign: 'right',
  },

  // ---- brand line on both sides ----
  brandLine: {
    fontFamily: 'Roboto',
    fontSize: 7,
    color: '#888888',
    textAlign: 'center',
    paddingBottom: 2,
  },
});